[project]
name = "arc-agi"
description = "Arc AGI"
channels = ["nvidia/label/cuda-11.8.0", "nvidia", "conda-forge", "pytorch"]
platforms = ["linux-64"]

[system-requirements]
libc = { family="glibc", version="2.30" }

[tasks]
# || operator in pixi allows running a command after only if the command before || fails
uv-install = "python -m pip install uv"
make-third_party-dir = {cmd="ls third_party || mkdir third_party"}
clone-arckit = {cmd="ls arckit || git clone --recursive https://github.com/mxbi/arckit.git", cwd = "third_party", depends_on=["make-third_party-dir"] }
clone-arcle = {cmd="ls arcle || git clone --recursive https://github.com/ConfeitoHS/arcle.git", cwd = "third_party", depends_on=["make-third_party-dir"] }

arcle-install = {cmd="python -c 'import arcle' || python -m uv pip install arcle", depends_on=["uv-install"]}
arckit-install = {cmd="python -c 'import arckit' || python -m uv pip install arckit", depends_on=["uv-install"]}
post-install = {cmd="pwd", depends_on=["arcle-install", "arckit-install", "clone-arckit", "clone-arcle"]}


[dependencies]
python = ">=3.9,<3.11"
pip = ">=24.0,<25"
cuda = {version = "*", channel="nvidia/label/cuda-11.8.0"}
pytorch-cuda = {version = "11.8.*", channel="pytorch"}
pytorch = {version = ">=2.2.0,<2.3", channel="pytorch"}
torchvision = {version = ">=0.17.0,<0.18", channel="pytorch"}
pyarrow = ">=15.0.2,<15.1"
numpy = "<2.0.0"


[pypi-dependencies]
